name: Python loop on

on: push

jobs:
  looping_num:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local code
        uses: actions/checkout@v3

      - name: Print numbers
        run: |
          docker ps
          docker login -u ${{ secrets.USERNAME }} -p fMmcG842tFP5Qk5
          ls

          docker build -t pythonappnew:1.0 .

          docker tag pythonappnew:1.0 dockertry1729/pythonappnew:1.0

          docker push dockertry1729/pythonappnew:1.0