name: Python loop on

on: push

jobs:
  looping_num:
    runs-on: ubuntu-latest
    steps:
      - name: Print numbers
        run: |
          docker ps
          docker login -u dockertry1729 -p fMmcG842tFP5Qk5