name: Python loop on

on: push

jobs:
  looping_num:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local code
        uses: actions/checkout@v3

      # - name: Print numbers
      #   run: |
      #     docker ps
      #     docker login -u ${{ secrets.USERNAME }} -p fMmcG842tFP5Qk5
      #     ls

      #     docker build -t pythonappnew:1.0 .

      #     docker tag pythonappnew:1.0 dockertry1729/pythonappnew:1.0

      #     docker push dockertry1729/pythonappnew:1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockertry1729/app:latest